/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BatchStock"
      | "InventoryTx"
      | "MAN"
      | "Manufacturing"
      | "Owner"
      | "ProductRequests"
      | "ProductStock"
      | "RET"
      | "Retail"
      | "WAR"
      | "Warehouse"
      | "addManufacturer"
      | "addProduct"
      | "addRetailer"
      | "addWarehouse"
      | "adjustInventory"
      | "batchBalanceByHolder"
      | "batchCtr"
      | "createBatch"
      | "fulfillBackorderAsAdmin"
      | "getBatchRemainingQty"
      | "getProductBatchIds"
      | "getProductTimestamps"
      | "inventoryTxCtr"
      | "isBatchExpired"
      | "isRetailer"
      | "issueInventory"
      | "manCtr"
      | "productCreatedAt"
      | "productCtr"
      | "productInventory"
      | "productLastUpdatedAt"
      | "productStageAt"
      | "receiveInventory"
      | "requestCtr"
      | "requestProduct"
      | "retCtr"
      | "showStage"
      | "sold"
      | "transferInventory"
      | "warCtr"
      | "warehouseAddStock"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchCreated"
      | "InventoryChanged"
      | "ProductOrdered"
      | "ProductRequestCreated"
      | "ProductRequestRoutedToManufacturing"
      | "ProductRequestUpdated"
      | "ProductStageUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BatchStock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "InventoryTx",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "MAN", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "Manufacturing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "Owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ProductRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ProductStock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "RET", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "Retail",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "WAR", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "Warehouse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addProduct",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addRetailer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addWarehouse",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "adjustInventory",
    values: [BigNumberish, BigNumberish, BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchBalanceByHolder",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "batchCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createBatch",
    values: [BigNumberish, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillBackorderAsAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchRemainingQty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductBatchIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductTimestamps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "inventoryTxCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBatchExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRetailer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueInventory",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "manCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "productCreatedAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "productInventory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productLastUpdatedAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productStageAt",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveInventory",
    values: [BigNumberish, BigNumberish, BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestProduct",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "retCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "showStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sold", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferInventory",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "warCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "warehouseAddStock",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BatchStock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "InventoryTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "Manufacturing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ProductRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ProductStock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Retail", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WAR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Warehouse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addRetailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addWarehouse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adjustInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchBalanceByHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillBackorderAsAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchRemainingQty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductBatchIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inventoryTxCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBatchExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRetailer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productCreatedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "productCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productLastUpdatedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productStageAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requestCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "retCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "showStage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "warCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "warehouseAddStock",
    data: BytesLike
  ): Result;
}

export namespace BatchCreatedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    productId: BigNumberish,
    batchNumber: string,
    supplierBatchRef: string,
    mfgDate: BigNumberish,
    expiryDate: BigNumberish,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    productId: bigint,
    batchNumber: string,
    supplierBatchRef: string,
    mfgDate: bigint,
    expiryDate: bigint,
    createdAt: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    productId: bigint;
    batchNumber: string;
    supplierBatchRef: string;
    mfgDate: bigint;
    expiryDate: bigint;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InventoryChangedEvent {
  export type InputTuple = [
    txId: BigNumberish,
    productId: BigNumberish,
    batchId: BigNumberish,
    action: BigNumberish,
    quantity: BigNumberish,
    signedDelta: BigNumberish,
    fromAddr: AddressLike,
    toAddr: AddressLike,
    refNote: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    txId: bigint,
    productId: bigint,
    batchId: bigint,
    action: bigint,
    quantity: bigint,
    signedDelta: bigint,
    fromAddr: string,
    toAddr: string,
    refNote: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    txId: bigint;
    productId: bigint;
    batchId: bigint;
    action: bigint;
    quantity: bigint;
    signedDelta: bigint;
    fromAddr: string;
    toAddr: string;
    refNote: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductOrderedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    name: string,
    timestamp: BigNumberish,
    actor: AddressLike
  ];
  export type OutputTuple = [
    productId: bigint,
    name: string,
    timestamp: bigint,
    actor: string
  ];
  export interface OutputObject {
    productId: bigint;
    name: string;
    timestamp: bigint;
    actor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRequestCreatedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    retailer: AddressLike,
    productId: BigNumberish,
    productName: string,
    status: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    retailer: string,
    productId: bigint,
    productName: string,
    status: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    retailer: string;
    productId: bigint;
    productName: string;
    status: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRequestRoutedToManufacturingEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    productId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    productId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    productId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRequestUpdatedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    status: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    status: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    status: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductStageUpdatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    fromStage: BigNumberish,
    toStage: BigNumberish,
    timestamp: BigNumberish,
    actor: AddressLike
  ];
  export type OutputTuple = [
    productId: bigint,
    fromStage: bigint,
    toStage: bigint,
    timestamp: bigint,
    actor: string
  ];
  export interface OutputObject {
    productId: bigint;
    fromStage: bigint;
    toStage: bigint;
    timestamp: bigint;
    actor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BatchStock: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        productId: bigint;
        batchNumber: string;
        supplierBatchRef: string;
        mfgDate: bigint;
        expiryDate: bigint;
        totalReceived: bigint;
        totalIssued: bigint;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  InventoryTx: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        productId: bigint;
        batchId: bigint;
        action: bigint;
        quantity: bigint;
        fromAddr: string;
        toAddr: string;
        signedDelta: bigint;
        refNote: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  MAN: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  Manufacturing: TypedContractMethod<
    [_productID: BigNumberish],
    [void],
    "nonpayable"
  >;

  Owner: TypedContractMethod<[], [string], "view">;

  ProductRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        retailerAddr: string;
        retailerId: bigint;
        productId: bigint;
        productName: string;
        description: string;
        status: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        linkedFulfillmentProductId: bigint;
      }
    ],
    "view"
  >;

  ProductStock: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint] & {
        id: bigint;
        name: string;
        description: string;
        MANid: bigint;
        WARid: bigint;
        RETid: bigint;
        stage: bigint;
      }
    ],
    "view"
  >;

  RET: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  Retail: TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;

  WAR: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  Warehouse: TypedContractMethod<
    [_productID: BigNumberish],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addProduct: TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;

  addRetailer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addWarehouse: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  adjustInventory: TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchID: BigNumberish,
      _quantityDelta: BigNumberish,
      _holder: AddressLike,
      _reference: string
    ],
    [void],
    "nonpayable"
  >;

  batchBalanceByHolder: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  batchCtr: TypedContractMethod<[], [bigint], "view">;

  createBatch: TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchNumber: string,
      _supplierBatchRef: string,
      _mfgDate: BigNumberish,
      _expiryDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  fulfillBackorderAsAdmin: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBatchRemainingQty: TypedContractMethod<
    [_batchID: BigNumberish],
    [bigint],
    "view"
  >;

  getProductBatchIds: TypedContractMethod<
    [_productID: BigNumberish],
    [bigint[]],
    "view"
  >;

  getProductTimestamps: TypedContractMethod<
    [_productID: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        orderedAt: bigint;
        manufactureAt: bigint;
        warehouseAt: bigint;
        retailAt: bigint;
        soldAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  inventoryTxCtr: TypedContractMethod<[], [bigint], "view">;

  isBatchExpired: TypedContractMethod<
    [_batchID: BigNumberish],
    [boolean],
    "view"
  >;

  isRetailer: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  issueInventory: TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchID: BigNumberish,
      _quantity: BigNumberish,
      _from: AddressLike,
      _to: AddressLike,
      _reference: string
    ],
    [void],
    "nonpayable"
  >;

  manCtr: TypedContractMethod<[], [bigint], "view">;

  productCreatedAt: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  productCtr: TypedContractMethod<[], [bigint], "view">;

  productInventory: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  productLastUpdatedAt: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  productStageAt: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  receiveInventory: TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchID: BigNumberish,
      _quantity: BigNumberish,
      _to: AddressLike,
      _reference: string
    ],
    [void],
    "nonpayable"
  >;

  requestCtr: TypedContractMethod<[], [bigint], "view">;

  requestProduct: TypedContractMethod<
    [name: string, description: string],
    [void],
    "nonpayable"
  >;

  retCtr: TypedContractMethod<[], [bigint], "view">;

  showStage: TypedContractMethod<[_productID: BigNumberish], [string], "view">;

  sold: TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;

  transferInventory: TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchID: BigNumberish,
      _quantity: BigNumberish,
      _from: AddressLike,
      _to: AddressLike,
      _reference: string
    ],
    [void],
    "nonpayable"
  >;

  warCtr: TypedContractMethod<[], [bigint], "view">;

  warehouseAddStock: TypedContractMethod<
    [_productID: BigNumberish, _quantity: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BatchStock"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        productId: bigint;
        batchNumber: string;
        supplierBatchRef: string;
        mfgDate: bigint;
        expiryDate: bigint;
        totalReceived: bigint;
        totalIssued: bigint;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "InventoryTx"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        productId: bigint;
        batchId: bigint;
        action: bigint;
        quantity: bigint;
        fromAddr: string;
        toAddr: string;
        signedDelta: bigint;
        refNote: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "MAN"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Manufacturing"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "Owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ProductRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        retailerAddr: string;
        retailerId: bigint;
        productId: bigint;
        productName: string;
        description: string;
        status: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        linkedFulfillmentProductId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ProductStock"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint] & {
        id: bigint;
        name: string;
        description: string;
        MANid: bigint;
        WARid: bigint;
        RETid: bigint;
        stage: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "RET"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Retail"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "WAR"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Warehouse"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addProduct"
  ): TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRetailer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addWarehouse"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adjustInventory"
  ): TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchID: BigNumberish,
      _quantityDelta: BigNumberish,
      _holder: AddressLike,
      _reference: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchBalanceByHolder"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createBatch"
  ): TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchNumber: string,
      _supplierBatchRef: string,
      _mfgDate: BigNumberish,
      _expiryDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fulfillBackorderAsAdmin"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBatchRemainingQty"
  ): TypedContractMethod<[_batchID: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProductBatchIds"
  ): TypedContractMethod<[_productID: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProductTimestamps"
  ): TypedContractMethod<
    [_productID: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        orderedAt: bigint;
        manufactureAt: bigint;
        warehouseAt: bigint;
        retailAt: bigint;
        soldAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "inventoryTxCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isBatchExpired"
  ): TypedContractMethod<[_batchID: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRetailer"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueInventory"
  ): TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchID: BigNumberish,
      _quantity: BigNumberish,
      _from: AddressLike,
      _to: AddressLike,
      _reference: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "manCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "productCreatedAt"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "productCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "productInventory"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "productLastUpdatedAt"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "productStageAt"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiveInventory"
  ): TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchID: BigNumberish,
      _quantity: BigNumberish,
      _to: AddressLike,
      _reference: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestProduct"
  ): TypedContractMethod<
    [name: string, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "retCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "showStage"
  ): TypedContractMethod<[_productID: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "sold"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferInventory"
  ): TypedContractMethod<
    [
      _productID: BigNumberish,
      _batchID: BigNumberish,
      _quantity: BigNumberish,
      _from: AddressLike,
      _to: AddressLike,
      _reference: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "warCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "warehouseAddStock"
  ): TypedContractMethod<
    [_productID: BigNumberish, _quantity: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchCreated"
  ): TypedContractEvent<
    BatchCreatedEvent.InputTuple,
    BatchCreatedEvent.OutputTuple,
    BatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InventoryChanged"
  ): TypedContractEvent<
    InventoryChangedEvent.InputTuple,
    InventoryChangedEvent.OutputTuple,
    InventoryChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProductOrdered"
  ): TypedContractEvent<
    ProductOrderedEvent.InputTuple,
    ProductOrderedEvent.OutputTuple,
    ProductOrderedEvent.OutputObject
  >;
  getEvent(
    key: "ProductRequestCreated"
  ): TypedContractEvent<
    ProductRequestCreatedEvent.InputTuple,
    ProductRequestCreatedEvent.OutputTuple,
    ProductRequestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProductRequestRoutedToManufacturing"
  ): TypedContractEvent<
    ProductRequestRoutedToManufacturingEvent.InputTuple,
    ProductRequestRoutedToManufacturingEvent.OutputTuple,
    ProductRequestRoutedToManufacturingEvent.OutputObject
  >;
  getEvent(
    key: "ProductRequestUpdated"
  ): TypedContractEvent<
    ProductRequestUpdatedEvent.InputTuple,
    ProductRequestUpdatedEvent.OutputTuple,
    ProductRequestUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProductStageUpdated"
  ): TypedContractEvent<
    ProductStageUpdatedEvent.InputTuple,
    ProductStageUpdatedEvent.OutputTuple,
    ProductStageUpdatedEvent.OutputObject
  >;

  filters: {
    "BatchCreated(uint256,uint256,string,string,uint256,uint256,uint256)": TypedContractEvent<
      BatchCreatedEvent.InputTuple,
      BatchCreatedEvent.OutputTuple,
      BatchCreatedEvent.OutputObject
    >;
    BatchCreated: TypedContractEvent<
      BatchCreatedEvent.InputTuple,
      BatchCreatedEvent.OutputTuple,
      BatchCreatedEvent.OutputObject
    >;

    "InventoryChanged(uint256,uint256,uint256,uint8,uint256,int256,address,address,string,uint256)": TypedContractEvent<
      InventoryChangedEvent.InputTuple,
      InventoryChangedEvent.OutputTuple,
      InventoryChangedEvent.OutputObject
    >;
    InventoryChanged: TypedContractEvent<
      InventoryChangedEvent.InputTuple,
      InventoryChangedEvent.OutputTuple,
      InventoryChangedEvent.OutputObject
    >;

    "ProductOrdered(uint256,string,uint256,address)": TypedContractEvent<
      ProductOrderedEvent.InputTuple,
      ProductOrderedEvent.OutputTuple,
      ProductOrderedEvent.OutputObject
    >;
    ProductOrdered: TypedContractEvent<
      ProductOrderedEvent.InputTuple,
      ProductOrderedEvent.OutputTuple,
      ProductOrderedEvent.OutputObject
    >;

    "ProductRequestCreated(uint256,address,uint256,string,uint8,uint256)": TypedContractEvent<
      ProductRequestCreatedEvent.InputTuple,
      ProductRequestCreatedEvent.OutputTuple,
      ProductRequestCreatedEvent.OutputObject
    >;
    ProductRequestCreated: TypedContractEvent<
      ProductRequestCreatedEvent.InputTuple,
      ProductRequestCreatedEvent.OutputTuple,
      ProductRequestCreatedEvent.OutputObject
    >;

    "ProductRequestRoutedToManufacturing(uint256,uint256,uint256)": TypedContractEvent<
      ProductRequestRoutedToManufacturingEvent.InputTuple,
      ProductRequestRoutedToManufacturingEvent.OutputTuple,
      ProductRequestRoutedToManufacturingEvent.OutputObject
    >;
    ProductRequestRoutedToManufacturing: TypedContractEvent<
      ProductRequestRoutedToManufacturingEvent.InputTuple,
      ProductRequestRoutedToManufacturingEvent.OutputTuple,
      ProductRequestRoutedToManufacturingEvent.OutputObject
    >;

    "ProductRequestUpdated(uint256,uint8,uint256)": TypedContractEvent<
      ProductRequestUpdatedEvent.InputTuple,
      ProductRequestUpdatedEvent.OutputTuple,
      ProductRequestUpdatedEvent.OutputObject
    >;
    ProductRequestUpdated: TypedContractEvent<
      ProductRequestUpdatedEvent.InputTuple,
      ProductRequestUpdatedEvent.OutputTuple,
      ProductRequestUpdatedEvent.OutputObject
    >;

    "ProductStageUpdated(uint256,uint8,uint8,uint256,address)": TypedContractEvent<
      ProductStageUpdatedEvent.InputTuple,
      ProductStageUpdatedEvent.OutputTuple,
      ProductStageUpdatedEvent.OutputObject
    >;
    ProductStageUpdated: TypedContractEvent<
      ProductStageUpdatedEvent.InputTuple,
      ProductStageUpdatedEvent.OutputTuple,
      ProductStageUpdatedEvent.OutputObject
    >;
  };
}
